baseURL = "https://1bit1nfo.netlify.app/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "1bit1nfo"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "Un bit de información cada día"
author = "Celia García Márquez"
copyright = "2020-2021"
description = "Blog sobre informática"
profilePicture = "images/avatar_red.jpg"
keywords = "informática"
favicon = "favicons"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
images = ["images/avatar_red.jpg"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
# indexDateFormat = "Mon, Jan 2, 2006"
# listDateFormat = "Jan 2"
# singleDateFormat = "Mon, Jan 2, 2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"

[params.simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/cgmarquez/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/CeliaGMqrz"


[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:cg.marquez95@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Inicio"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "Sobre mí"
  weight = 300
  identifier = "about"
  url = "/about/"


